services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  n8n-python:
    image: n8n-python
    build: ./n8n
    container_name: n8n-python_container
    restart: always
    env_file:
      - .env
    ports:
      - 5678:5678
    volumes:
      - ./n8n/data:/home/node/.n8n
    depends_on:
      - postgres

  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    restart: always
    env_file:
      - .env
    ports:
      - 5050:80
    volumes:
      - ./pgadmin/data:/var/lib/pgadmin
    depends_on:
      - postgres

  caddy:
    image: caddy:latest
    container_name: caddy_container
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
